export declare enum FlowElementType {
  ADD_TAG = "ADD_TAG",
  ADD_TO_BLACKLIST = "ADD_TO_BLACKLIST",
  CALL_URL = "CALL_URL",
  COLLECT_IVR_ACTION = "COLLECT_IVR_ACTION",
  DIAL_IVR_ACTION = "DIAL_IVR_ACTION",
  EVALUATE_EVENT = "EVALUATE_EVENT",
  EVALUATE_INBOUND_MESSAGE = "EVALUATE_INBOUND_MESSAGE",
  EVALUATE_VALUE = "EVALUATE_VALUE",
  EXIT = "EXIT",
  FAILOVER_ACTION = "FAILOVER_ACTION",
  IVR_HANG_UP = "IVR_HANG_UP",
  NEW_ELEMENT = "NEW_ELEMENT",
  PAUSE = "PAUSE",
  PLAY_IVR_ACTION = "PLAY_IVR_ACTION",
  RECORD_IVR_ACTION = "RECORD_IVR_ACTION",
  REMOVE_FROM_BLACKLIST = "REMOVE_FROM_BLACKLIST",
  REMOVE_TAG = "REMOVE_TAG",
  SEND_ACTION = "SEND_ACTION",
  START = "START",
  START_CALL_IVR_ACTION = "START_CALL_IVR_ACTION",
  START_CONVERSATION = "START_CONVERSATION",
  START_EVALUATE_INBOUND_MESSAGE = "START_EVALUATE_INBOUND_MESSAGE",
  START_EVALUATE_PEOPLE_EVENT = "START_EVALUATE_PEOPLE_EVENT",
  START_FLOW_WEBHOOK = "START_FLOW_WEBHOOK",
  START_IVR_INBOUND = "START_IVR_INBOUND",
  START_RESOLVE_ONETIME_AUDIENCE = "START_RESOLVE_ONETIME_AUDIENCE",
  START_EVALUATE_BEHAVIOUR_EVENT = "START_EVALUATE_BEHAVIOUR_EVENT",
  START_EVALUATE_ATTRIBUTE_EVENT = "START_EVALUATE_ATTRIBUTE_EVENT",
  EVALUATE_BEHAVIOUR_EVENT = "EVALUATE_BEHAVIOUR_EVENT",
  EVALUATE_ATTRIBUTE_EVENT = "EVALUATE_ATTRIBUTE_EVENT",
  EVALUATE_PARTICIPANT_DATA = "EVALUATE_PARTICIPANT_DATA",
  EVALUATE_EMAIL_EVENT = "EVALUATE_EMAIL_EVENT",
  PERFORM_EXPERIMENT_ACTION = "PERFORM_EXPERIMENT_ACTION"
}

export interface FlowElementPreview {
  icon: string;
  title: string;
  content: string;
  rulesContent?: string[];
}